travis:
  secure:
    BINSTAR_TOKEN: q4I4g0QGr1eeFW7Aspdm6z101ijEXBLjTQIvh2lgWkVH3aI4UilkGK9Mdcp1jqfnRECs8ou1pZCE2MKBCAGCEs2fOUlzgNQnQOp1O24AxE4B7UfwNjcJkkI7sC+4xaK74yEQyuMB5LhEm+8aImdy5njQ0JLqWo7OuGQUI0K7cJS56rfR4fPa9y+HoEih6mKAHIZ2jOBBPzArRff46mzEYJSnTnnA1uzEmTO1yXXQU6g5q1gUTyVPVgIIuraC3m3PFNek9TywmhwRTdz1jnTOo8PCdEBXP3Bae0k1SLMvet+ESDmSPGEAs/RyGJ58+0lCYTWytPwQH9jx6z97+1/H0JwPSkJ4GLZPIGuy+Yv1LJwu7+p4uFYxlqcocpSFY8txeUv5VnRjolDzW8rVNQ0WIAtXFjTyd1z5spJL8fhP4Sin3/imXaaksaYfVz1BNDpubVT6NsSRthAZEWmRGTOeaoELm2w8RA7gvkeVgqTx2r/F3H6tNwp/IB99yDO9WlN7u6NfgZFkIbOMB8MJOKGsP4Eu2nrVtTFGDOT0YDMB4sV51tH5Yed7Dmm6Jga0akseIRS9g883odBNHbY7n0SHQDsl/atUfTAqLlP4CelsNPdh8psE2xVX3YyVnKyOsvIHRTq/IKyXRiZwUiJxUxCwKTaBcgrdFd9XtitmdIc2vus=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
